version: '3.8'

services:
  fastai-dev:
    build: .
    runtime: nvidia
    ports:
      - "8888:8888"
    volumes:
      - ./:/app/notebooks  # 挂载代码文件夹
      - ./config/:/root/.jupyter/ # 挂载Jupyter配置文件
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
