version: '3'
services:
  fastai-notebook:
    image: fastai/fastai:latest
    ports:
      - "8888:8888"
    volumes:
      - ./code:/workspace/code  # 挂载代码文件夹
      - ./config:/root/.jupyter # 挂载Jupyter配置文件
    command: ["jupyter", "notebook", "--ip=0.0.0.0", "--port=8888", "--allow-root", "--NotebookApp.token=''"]
    environment:
      - NVIDIA_VISIBLE_DEVICES=all

